### ISSUE TITLE
Agregar proyecto

### ISSUE THREAD

**Issue by mariabda2** [bimbau/issues-report#10]
Descripción:
Una vez logeada y después de ir al Catálogo, me sale el mensaje de “Selecciona Proyecto”.
Cuando miras si tienes a la mano, donde agregar proyecto, no sale donde iniciar a agregar la información del proyecto. 
¿cómo se agrega? No es intuitivo. Adjunto la imagen de lo que se me desplegó.

Url:
https://test.bimbau.co/library

Imágenes:
https://drive.google.com/file/d/1aNROkBDMe3ZeCx5qUpnjV9T90BUEqqV5/view?usp=drivesdk

**Comment by FiorellaRomero** [comment]
Ya está en responsive la parte de crear proyectos.
