### ISSUE TITLE
Ir a librería Bim

### ISSUE THREAD

**Issue by mariabda2** [bimbau/issues-report#11]
Descripción: 
El botón “ir a librería BIM” lleva a la página de inicio pero no al grupo de productos que tienen modelo BIM (suponiendo que esa fuera la función)

URL:
https://test.bimbau.co/library

Imagen:
https://drive.google.com/file/d/1VWMNViBOV2qCpCpNBDluTZUU7vrVMKg5/view?usp=drivesdk

**Comment by FiorellaRomero** [comment]
El botón de "Ir a la librería BIM" redirecciona al catálogo, así es el funcionamiento.

**Comment by mariabda2** [comment]
Pero debería ser al catálogo de productos BIM. Es confuso el nombre del botón si direcciona al catálogo en general.
