### ISSUE TITLE
Categoría elementos de distribución

### ISSUE THREAD

**Issue by BIMBAU13** [bimbau/issues-report#12]
La categoría elementos de distribución se refiere a los productos generales que hacen parte de las instalaciones de una edificación que son del area MEP ( Mechanical, Electrical and Plumbing, HVAC) como:  Plomería, distribución de aire acondicionado, Productos eléctricos e iluminación, comunicaciones, red contra incendio. Por lo cual considero que el símbolo del carrito que tiene en la imagen puede confundir y no hace referencia real a los elementos de la categoría.
![Captura de pantalla (428)_LI](https://user-images.githubusercontent.com/91079710/146957571-b0460326-1252-4bc6-9d64-9170e2db44c4.jpg)
)

**Comment by FiorellaRomero** [comment]
Icono actualizado.

<img width="187" alt="Icon" src="https://user-images.githubusercontent.com/89941870/147146980-421742be-b385-4c3a-9dcb-14ee42f6f9e7.PNG">
