### ISSUE TITLE
Categoría equipamiento y suministro

### ISSUE THREAD

**Issue by BIMBAU13** [bimbau/issues-report#13]
La categoría equipamiento y suministro, según las tablas OMNICLASS hace referencia a la categoría Equipment and furnishing, que traducido seria Equipamiento y mobiliario. Es solo una observación para revisar la traducción, ya que equipamiento y suministro no se entiende a que hace referencia.
![Captura de pantalla (429)_LI](https://user-images.githubusercontent.com/91079710/146958397-19b7f245-b1a8-493c-b72f-05f59446cd05.jpg)

**Comment by FiorellaRomero** [comment]
Nombre de la categoría actualizado

![image](https://user-images.githubusercontent.com/89941870/147147360-dc7b5750-273d-4817-8dd5-1fa768876532.png)
