### ISSUE TITLE
Ortografía  mensaje Cookies

### ISSUE THREAD

**Issue by mariabda2** [bimbau/issues-report#3]
**Descripción del issue:** 
Falta una "coma" en la última frase del párrafo, luego de la palabra, continuación.
Resalté en la imagen compartida, donde debería ir la coma ",".

**URL de donde se da el problema:** 
https://test.bimbau.co/library

**Link imagen:** 
https://drive.google.com/file/d/15lY5FJYeigZ2eQfmNxtULDG6TfxBUFDt/view?usp=sharing

**Comment by FiorellaRomero** [comment]
Mensaje corregido.

![image](https://user-images.githubusercontent.com/89941870/147249600-4bb3b5c1-f076-4ce9-bf14-08e3cd54c5c4.png)
