### ISSUE TITLE
Distribución de imágenes panel de entrada

### ISSUE THREAD

**Issue by mariabda2** [bimbau/issues-report#4]
Descripción del issue:
Más que issue es una duda, la distribución de las imágenes deja un hueco en la página, eso es normal o ¿debería reorganizarse para utilizar todo el espacio? 
Yo resalté en la imagen los espacios que se ven raro vacíos. Miré en varios PC y no se reacomoda en pantalla completa.
Zoom: 100%

URL de donde se da el problema:
https://test.bimbau.co/library

Link imagen:
https://drive.google.com/file/d/15vCKpRSK4_Zz97OhIY9OyWKOVwQroyP2/view?usp=sharing

**Comment by FiorellaRomero** [comment]
Esto se presenta por la configuración recomendada de la pantalla del computador.
