### ISSUE TITLE
Impresión duplicada de imagen opciones de variante 

### ISSUE THREAD

**Issue by mariabda2** [bimbau/issues-report#6]
Descripción del issue:
Al seleccionar un producto que tiene variantes, sale duplicada la imagen de la variable en la parte inferior. Esos iconos no son funcionales, es decir, al seleccionarlos no cambia la imagen que se muestra de la variante ni la información de la misma. Es como un efecto espejo 😅
Los he resaltado en la imagen.

URL de donde se da el problema:

> https://test.bimbau.co/library/product/tubo-extensor-lvm-25cm-10098?url=%2Flibrary%2Fcategory%3FisBIM%3Dtrue&pj=

> https://test.bimbau.co/library/product/overol-obras-9969?url=%2Flibrary%2Fcategory%3FisBIM%3Dtrue&pj=

Link imagen:

> https://drive.google.com/file/d/1svv1Mp2mlkS4cVy4FKEVflonLVKa5VRL/view?usp=drivesdk

> https://drive.google.com/file/d/1-0aHck_cFfg-sdL2VsGZT5hUOEtnS5wd/view?usp=drivesdk

**Comment by FiorellaRomero** [comment]
Ya las imágenes no se duplican.

![image](https://user-images.githubusercontent.com/89941870/147265145-92f28605-3bc5-44ea-a304-f9829a010276.png)
