### ISSUE TITLE
Mensaje cuando no hay información detallada del producto

### ISSUE THREAD

**Issue by mariabda2** [bimbau/issues-report#7]
Descripción del issue:
No es un problema, pero podría unificarse la información. Cuando no hay detalles sobre la información de un producto en algunos ítems se dice “no hay anexos…”, “no hay información… “
Pero hay algunas veces que está vacío, se podría indicar que “no hay información…” para unificar todas las características que se imprimen.
Resalto lo que menciono en las imágenes. 

URL de donde se da el problema:
https://test.bimbau.co/library/product/overol-obras-9969?url=%2Flibrary%2Fcategory%3FisBIM%3Dtrue&pj=

Link imágenes: 
> https://drive.google.com/file/d/1JsrvC7kBZu4QxubaRzmiU9MpUBFoCslw/view?usp=drivesdk

> https://drive.google.com/file/d/1hvlNWgnkRhmTWQLAvBRToTA7X62ukvmp/view?usp=drivesdk

> https://drive.google.com/file/d/1ePz1e8mlDXSiibG3pvKq0U8xrk20Qo9P/view?usp=drivesdk

**Comment by FiorellaRomero** [comment]
Mensajes añadidos.

![image](https://user-images.githubusercontent.com/89941870/147259076-5c4572a7-e0ff-4c2a-8c1e-ced8f1af9a2d.png)

![image](https://user-images.githubusercontent.com/89941870/147259116-088d82b6-9857-44e8-8011-11438db6c109.png)
