### ISSUE TITLE
No se imprime el dígito cero en la descripción 

### ISSUE THREAD

**Issue by mariabda2** [bimbau/issues-report#8]
Descripción del issue:
En las dimensiones del producto, no se imprime el dígito cero si el valor es menor a 1

URL:
https://test.bimbau.co/library/product/bloque-n5-tradicional-2274?url=%2Flibrary%2Fcategory%2Fbuilding-elements-31&pj=

https://test.bimbau.co/library/product/ladrillo-bloque-estructural-pv-rojo-pared-sencilla-mf-2268?url=%2Flibrary%2Fcategory%2Fbuilding-elements-31&pj=

Imágenes:
https://drive.google.com/file/d/1kA-FX45t7nEFVEgQpd-D_2o9Zw7MKx8N/view?usp=drivesdk

https://drive.google.com/file/d/14uOgZztVB-ROJoiS9-5VQWUjMA67g15u/view?usp=drivesdk

**Comment by FiorellaRomero** [comment]
La descripción de producto la sube el usuario al cargar productos, se muestra tal cual el usuario la redacta.
