### ISSUE TITLE
Mensaje de Bienvenida después de registrada 

### ISSUE THREAD

**Issue by mariabda2** [bimbau/issues-report#9]
Descripción:
Mensaje de bienvenida después de registrarse. Sale desorganizado en la pantalla. Ingresé desde el celular (iPhone)

url:
https://test.bimbau.co/company/preferences

Imágenes:
https://drive.google.com/file/d/1F_vHOoCb1o90T7z-_H4ADkfu8swM1oti/view?usp=drivesdk

https://drive.google.com/file/d/17TO7UEy_717gnuivFV1dLBApKnDD_oG2/view?usp=drivesdk

**Comment by FiorellaRomero** [comment]
Ya está el responsive de esta pantalla.
